app/urls.py
from django.conf.urls import patterns, include, url
import settings

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
   url(r'^$', 'app.social.views.main'),

   ## social app
   url(r'', include('app.social.urls')),

   ## registration
   url(r'', include('app.accounts.urls')),
)

handler500 = 'app.social.views.error'

if settings.DEBUG == True:
   from django.contrib.staticfiles.urls import staticfiles_urlpatterns
   urlpatterns += staticfiles_urlpatterns()

app/social/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

PERSON_AGE_RANGE_CHOICES = (
   ('1','10-19'),
   ('2','20-29'),
   ('3','30-39'),
   ('4','40-49'),
   ('5','50-59'),
   ('6','60-69'),
   ('7','70-79'),
   ('8','80+')
)

PERSON_GENDER_CHOICES = (
   ('m','Male'),
   ('f','Female'),
   ('o','Other')
)

PERSON_TYPE_CHOICES = (
   ('h','Highschool Student'),
   ('u','Undergraduate Student'),
   ('g','Graduate Student'),
   ('a','Academic'),
   ('p','Professional'),
   ('o','Other')
)

PERSON_LEARNING_STYLE_CHOICES = (
   ('v','Visual'),
   ('a','Auditory'),
   ('t','Tactile')
)

PERSON_INTEREST_CHOICES = (
   ('Agr','Agriculture'),
   ('Ant','Anthropology'),
   ('Arc','Archeology'),
   ('Arc','Architecture and Design'),
   ('Are','Area studies'),
   ('Bus','Business'),
   ('Che','Chemistry'),
   ('Com','Computer Sciences'),
   ('Cul','Cultural and Ethnic Studies'),
   ('Div','Divinity'),
   ('Ear','Earth Sciences'),
   ('Eco','Economics'),
   ('Edu','Education'),
   ('Eng','Engineering'),
   ('Env','Environmental Studies and Forestry'),
   ('Fam','Family and Consumer Science'),
   ('Gen','Gender and Sexuality Studies'),
   ('Geo','Geography'),
   ('Hea','Health Science'),
   ('His','History'),
   ('Hum','Human Physical Performance and Recreation'),
   ('Jou','Journalism, Media Studies and Communication'),
   ('Law','Law'),
   ('Lib','Library and Museum Studies'),
   ('Lif','Life Sciences'),
   ('Lin','Linguistics'),
   ('Lit','Literature'),
   ('Log','Logic'),
   ('Mat','Mathematics'),
   ('Mil','Military Sciences'),
   ('Per','Performing Arts'),
   ('Phi','Philosophy'),
   ('Phy','Physics'),
   ('Pol','Political Science'),
   ('Psy','Psychology'),
   ('Pub','Public Administration'),
   ('Rel','Religion'),
   ('Soc','Social Work'),
   ('Soc','Sociology'),
   ('Spa','Space Science'),
   ('Sta','Statistics'),
   ('Sys','Systems Science'),
   ('Tra','Transportation'),
   ('Vis','Visual Arts'),
   ('Oth','Other')
)

COURSE_SERVICE_CHOICES = (
   ('u','Udacity'),
   ('c','Coursera'),
   ('e','edX')
)

USER_COURSE_EXPERIENCE_CHOICES = (
   ('f','First Timer'),
   ('h','Hobbyist'),
   ('u','Undergraduate Student'),
   ('g','Graduate Student'),
   ('a','Academic'),
   ('p','Professional'),
   ('o','Other')
)

USER_COURSE_LEVEL_CHOICES = (
   ('n','Novice'),
   ('i','Intermediate'),
   ('e','Expert')
)

USER_COURSE_YEARS_CHOICES = (
   ('0','<1 year'),
   ('1','1-2 years'),
   ('2','2-5 years'),
   ('5','>5 years')
)

USER_COURSE_REASON_CHOICES = (
   ('n','Interest in new topic'),
   ('r','Refresher on topic'),
   ('b','Background for a new class'),
   ('e','Recommended by a friend/teacher'),
   ('t','Taking with a friend'),
   ('q','Required for a different course'),
   ('o','Other')
)

USER_COURSE_CREDIT_CHOICES = (
   ('y','Yes'),
   ('n','No')
)

USER_COURSE_GOAL_CHOICES = (
   ('g','Get a new job'),
   ('e','Gain experience in this topic'),
   ('c','Curiosity about a topic'),
   ('o','Other')
)

CIRCLE_ACTION_TYPES = (
   ('j','User joined'),
   ('c','User says')
)



class Course(models.Model):
   name = models.CharField(max_length=255)
   service = models.CharField(max_length=1,choices=COURSE_SERVICE_CHOICES)
   course_id = models.CharField(max_length=64)
   professor = models.CharField(max_length=255)
   url = models.URLField()

   students = models.ManyToManyField(User,through='UserCourse')

   def __unicode__(self):
      return '%s: %s'%(self.get_service_display(),self.name)

   class Meta:
      ordering = ['service', 'name']

class UserProfile(models.Model):
   user = models.OneToOneField(User, primary_key=True)
   age = models.CharField(
      max_length=1,
      choices=PERSON_AGE_RANGE_CHOICES,
      verbose_name="What is your age?")
   gender = models.CharField(
      max_length=1,
      choices=PERSON_GENDER_CHOICES,
      verbose_name="What is your gender?")
   person_type = models.CharField(
      max_length=1,
      choices=PERSON_TYPE_CHOICES,
      verbose_name="Which best describes you?")
   learning_style = models.CharField(
      max_length=1,
      choices=PERSON_LEARNING_STYLE_CHOICES,
      verbose_name="Which learning style best describes you?")
   interest = models.CharField(
      max_length=3,
      choices=PERSON_INTEREST_CHOICES,
      verbose_name="What is your area of interest?")
   monday_availability = models.CharField(max_length=48)
   tuesday_availability = models.CharField(max_length=48)
   wednesday_availability = models.CharField(max_length=48)
   thursday_availability = models.CharField(max_length=48)
   friday_availability = models.CharField(max_length=48)
   saturday_availability = models.CharField(max_length=48)
   sunday_availability = models.CharField(max_length=48)

   bio = models.CharField(max_length=140,verbose_name="Tell us a little about yourself, (140 characters remaining)")

def createUserProfile(sender, instance, **kwargs):
    """Create a UserProfile object each time a User is created ; and link it.
    """
    UserProfile.objects.get_or_create(user=instance)

post_save.connect(createUserProfile, sender=User)

class UserCourse(models.Model):
   user = models.ForeignKey(User)
   course = models.ForeignKey(Course)
   general_level = models.CharField(
      max_length=1,
      choices=USER_COURSE_LEVEL_CHOICES,
      verbose_name="What is your level for this course's general area of study?")
   topic_level = models.CharField(
      max_length=1,
      choices=USER_COURSE_LEVEL_CHOICES,
      verbose_name="What is your level for this course's specific topic?")
   years_experience = models.CharField(
      max_length=1,
      choices=USER_COURSE_YEARS_CHOICES,
      verbose_name="How many years of experience do you have in this area?")
   reason = models.CharField(
      max_length=1,
      choices=USER_COURSE_REASON_CHOICES,
      verbose_name="Why are you taking this course?")
   credit = models.CharField(
      max_length=1,
      choices=USER_COURSE_CREDIT_CHOICES,
      verbose_name="Are you taking this course for credit at any academic institution?")
   goals = models.CharField(
      max_length=1,
      choices=USER_COURSE_GOAL_CHOICES,
      verbose_name="What is your primary goal from taking this course?")
   
   class Meta:
      unique_together = ("user", "course")

class Circle(models.Model):
   course = models.ForeignKey(Course)
   users = models.ManyToManyField(User,through='CircleUser')
   requests = models.ManyToManyField(User,through='CircleRequest',related_name='circle_request')
   public = models.BooleanField(default=False)

   def __unicode__(self):
      people = map(lambda u: u.first_name, self.users.all())
      return '%s with %s'%(self.course,", ".join(people))

class CircleUser(models.Model):
   circle = models.ForeignKey(Circle)
   user = models.ForeignKey(User)
   video = models.BooleanField(default=False)
   last_video = models.DateTimeField(auto_now=True)
   created = models.DateTimeField(auto_now=True)

class CircleAction(models.Model):
   circle = models.ForeignKey(Circle)
   user = models.ForeignKey(User) 
   type = models.CharField(max_length=1,choices=CIRCLE_ACTION_TYPES)
   text = models.TextField(null=True)
   created = models.DateTimeField(auto_now=True)
def createUserJoinAction(sender, instance, **kwargs):
    """Create a user joined action when they join
    """
    action = CircleAction(circle=instance.circle,user=instance.user,type='j')
    action.save()
post_save.connect(createUserJoinAction, sender=CircleUser)

class CircleRequest(models.Model):
   circle = models.ForeignKey(Circle)
   owner = models.ForeignKey(User,related_name='circle_request_owner')
   confirmed = models.ManyToManyField(User,related_name='circle_request_confirmer')
   created = models.DateTimeField(auto_now=True)
   deleted = models.BooleanField(default=False)

class PartnerRequest(models.Model):
   course = models.ForeignKey(Course,related_name='+')
   owner = models.ForeignKey(User,related_name='partner_request_owner')
   user = models.ForeignKey(User,related_name='partner_request_user')
   created = models.DateTimeField(auto_now=True)
   deleted = models.BooleanField(default=False)

   def owner_usercourse(self):
      return self.owner.usercourse_set.get(course=self.course)

   def user_usercourse(self):
      return self.user.usercourse_set.get(course=self.course)

class PartnerSuggest(models.Model):
   course = models.ForeignKey(Course,related_name='+')
   owner = models.ForeignKey(User,related_name='partner_suggest_owner')
   user = models.ForeignKey(User,related_name='partner_suggest_user')
   created = models.DateTimeField(auto_now=True)
   deleted = models.BooleanField(default=False)

class CircleSuggest(models.Model):
   owner = models.ForeignKey(User,related_name='circle_suggest_owner')
   circle = models.ForeignKey(Circle,related_name='circle_suggest_circle')
   created = models.DateTimeField(auto_now=True)
   deleted = models.BooleanField(default=False)

social/models.py
from django.db import models
from django.contrib.auth.models import User

PERSON_TYPE_CHOICES = (('h','Highschool Student'),('u','Undergraduate Student'),('g','Graduate Student'),('p','Professional'),('r','Retired'),('o','Other'))

COURSE_SERVICE_CHOICES = (('u','Udacity'),('c','Coursera'),('e','edX'))

EXPERT_LEVEL_CHOICES = (('p','Professional'),('u','Undergraduate Student'),('g','Graduate Student'),('h','Hobbiest'),('f','First Timer'),('o','Other'))

EXPERT_TIME_CHOICES = (('0','<1'),('1','1-2'),('2','2-5'),('5','>5'))

NOVICE_INTERMEDIATE_EXPERT = (('n','Novice'),('i','Intermediate'),('e','expert_level'))

REASON_CHOICES = (('n','Interest in new topic'),('r','Refresher on topic'),('o','Other'))

class Person(User):
   person_type = models.CharField(max_length=1,choices=PERSON_TYPE_CHOICES)
   courses = models.ManyToManyField(Course,through=PersonCourses)


class Course(models.Model):
   name = models.CharField(max_length=255)
   service = models.CharField(max_length=1,choices=COURSE_SERVICE_CHOICES)
   course_id = models.CharField(max_length=64)
   url = models.UrlField()


class PersonCourses(models.Model):
   person = models.ForeignKey(Person)
   course = models.ForeignKey(Course)
   expert_level = models.CharField(max_length=1,choices=EXPERT_LEVEL_CHOICES)
   expert_time = models.CharField(max_length=1,choices=EXPERT_TIME_CHOICES)
   general_level = models.CharField(max_length=1,choices=NOVICE_INTERMEDIATE_EXPERT)
   specific_level = models.CharField(max_length=1,choices=NOVICE_INTERMEDIATE_EXPERT)
   reason = models.CharField(max_length=1,choices=REASON_CHOICES)
   

app/templates/courses.html
{% extends "base.html" %}
{% block content %}
<a href="/courses/add" class="btn btn-danger pull-right"><i class="icon-plus"></i> Add a course</a>
<h2>Your Courses</h2>
{% for c in courses %}   
   <div class="user-course well">
      <div class="options pull-right">
         <form action="/courses/drop/" method='post'>
            {% csrf_token %}
            <input type="hidden" name="usercourse_id" value="{{c.id}}">
            <button type="submit" class="btn btn-inverse">
               <i class="icon-trash"></i> Drop this course
            </button>
         </form>
      </div>
      <div class="service">{{c.course.get_service_display}}</div>
      <div class="title">{{c.course.name}}</div>
      <div class="homepage"><a href="{{c.course.url}}" target="_blank">Course Homepage</a></div>
   </div>
{% empty %}
<p>
   It looks like you haven't told us about any classes you are taking yet.
</p>
<p>
   Why don't you <a href="/courses/add">add one now</a>?
</p>
{% endfor %}
{% endblock %}

app/templates/courses_add.html
{% extends "base.html" %}
{% load bootstrap %}
{% block content %}
<div class="row">
   <div class="span6 offset3">
      <form class="well form-horizontal" method="post">
         <legend>Add a course</legend>
         {{ user_course_form|bootstrap }}
         {% csrf_token %}
         <div class="control-group">
            <div class="controls">
               <button type="submit" class="btn btn-primary">Add Course</button>
            </div>
         </div>
      </form>
   </div>
</div>
{% endblock %}

app/templates/explore.html
{% extends "base.html" %}
{% block content %}
<p>To find a group for a course choose from the list below:</p>
{% for c in courses %}
<p><a href="/explore/{{c.id}}" class="btn">{{c.course}}</a></p>
{% empty %}
<p>
   It looks like you haven't told us about any classes you are taking yet.
</p>
<p>
   Why don't you <a href="/courses/add">add one now</a>?
</p>
{% endfor %}
{% endblock %}

app/templates/explore_course.html
{% extends "base.html" %}
{% load bootstrap_pagination %}
{% load availability_check %}
{% block content %}
<h2>Find groups for your course <strong>{{usercourse.course}}</strong></h2>
{% if people %}
<div class="row">
  <div class="span4" style="position: relative;">
    <div data-spy="affix" style="width: 300px;">
      <div id="graph"></div>
      <div class="alert alert-info" id="viz-info">The black dot in the center represents you. Each other dot is another student enrolled in this course. The closer they are to you, they more similar they are to you.</div>
    </div>
  </div>
  <div class="span8">
    <div id="user-holder"></div>
    {% bootstrap_paginate people range=10 %}
  </div>
</div>
{% else %}
<p>It looks like no one else is enrolled in this course yet. Check back soon!</p>
{% endif %}
{% endblock %}
{% block bottom_script %}
<script src="{{STATIC_URL}}js/d3.v2.min.js"></script>

<script type="text/javascript">
var SMALL_RADIUS = 5;
var LARGE_RADIUS = 2*SMALL_RADIUS;

var user = {
  'age': '{{user.get_profile.get_age_display}}',
  'gender': '{{user.get_profile.get_gender_display}}',
  'person_type': '{{user.get_profile.get_person_type_display}}',
  'learning_style': '{{user.get_profile.get_learning_style_display}}',
  'interest': '{{user.get_profile.get_interest_display}}',
  'general_level': '{{usercourse.get_general_level_display}}',
  'topic_level': '{{usercourse.get_topic_level_display}}',
  'years_experience': '{{usercourse.get_years_experience_display}}',
  'reason': '{{usercourse.get_reason_display}}',
  'credit': '{{usercourse.get_credit_display}}',
  'goals': '{{usercourse.get_goals_display}}'
};

var people = [
  {% for p in people %}
  {
    'id': {{p.user.id}},
    'age': '{{p.user.get_profile.get_age_display}}',
    'gender': '{{p.user.get_profile.get_gender_display}}',
    'person_type': '{{p.user.get_profile.get_person_type_display}}',
    'learning_style': '{{p.user.get_profile.get_learning_style_display}}',
    'interest': '{{p.user.get_profile.get_interest_display}}',
    'bio': '{{p.user.get_profile.bio}}',
    'availability': {% availability_check p.user.get_profile user.get_profile "true" "false" %},
    'general_level': '{{p.get_general_level_display}}',
    'topic_level': '{{p.get_topic_level_display}}',
    'years_experience': '{{p.get_years_experience_display}}',
    'reason': '{{p.get_reason_display}}',
    'credit': '{{p.get_credit_display}}',
    'goals': '{{p.get_goals_display}}'
  }{% if not forloop.last %},{% endif %}
  {% endfor %}
];

var holder = $("#user-holder");
people.sort(function(a,b){
  return calculateDistance(a)-calculateDistance(b);
});
for(var i=0;i<people.length;i++){
  holder.append(drawUserBox(people[i]));
}

$(".request-group-form").submit(function(){
  var button = $(this).find('input[type="submit"]');
  button.val("Sending...");
  $.post('/groups/create/',$(this).serialize(),function(data){
    button.val(data['success']);
    button.removeClass('btn-primary');
    button.addClass('btn-success');
  });
  return false;
});

$(document).ready(function(){
  setTimeout(function(){
    $("#viz-info").fadeOut();
  },10000);
});


var h = 300,
    w = 300;

var nodes = people,
    color = d3.scale.category10();

var root = {
  x: 142, 
  y: 142, 
  color: '#000', 
  radius: LARGE_RADIUS,
  fixed: true
};

links = [];
for(var n in nodes){
  links.push({source: root, target: nodes[n]});
}

nodes.push(root);

var force = d3.layout.force()
    .gravity(0.01)
    .charge(-4)
    .nodes(nodes)
    .links(links)
    .linkDistance(function(d){
      return calculateDistance(d.target);
    })
    .size([w, h]);

force.start();

var svg = d3.select("#graph").append("svg:svg")
    .attr("width", w)
    .attr("height", h);

var node = svg.selectAll("circle")
    .data(nodes)
    .enter().append("svg:circle")
    .attr("r", function(d) { return d.radius || SMALL_RADIUS; })
    .attr("id",function(d) {return "user-node-"+d.id;})
    .on("mouseover",function(d){
      if(d != root){
        d3.select(this).attr("r",LARGE_RADIUS);
        $("#user-box-"+d.id).animate({
          borderTopColor:'#5192FB',
          borderLeftColor: '#5192FB',
          borderRightColor: '#5192FB',
          borderBottomColor: '#5192FB'
        },200);
        $('html, body').stop().animate({
          scrollTop: $("#user-box-"+d.id).offset().top-10
        }, 500);
      }
    })
    .on("mouseout",function(d){
      if(d != root){
        setTimeout(function(){
          $("#user-box-"+d.id).animate({
            borderTopColor:'transparent',
            borderLeftColor: 'transparent',
            borderRightColor: 'transparent',
            borderBottomColor: 'transparent'
          },200);
        },2000);
        
        d3.select(this).attr("r",SMALL_RADIUS);
      }
    })
    .style("fill", function(d, i) { return d.color || color(i % 10); });

force.on("tick", function(e) {
  node.attr("cx", function(d) { return d.x; })
      .attr("cy", function(d) { return d.y; });
});

$(".user-box").hover(function(){
  var id = $(this).data('user-id');
  svg.select("#user-node-"+id).attr("r",LARGE_RADIUS);
  $(this).animate({
    borderTopColor:'#5192FB',
    borderLeftColor: '#5192FB',
    borderRightColor: '#5192FB',
    borderBottomColor: '#5192FB'
  },200);
},function(){
  var id = $(this).data('user-id');
  svg.select("#user-node-"+id).attr("r",SMALL_RADIUS);
  $(this).animate({
    borderTopColor:'transparent',
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: 'transparent'
  },200);
});



function drawUserBox(user){
  return "<div class='well user-box' id='user-box-"+user.id+"' data-user-id='"+user.id+"'>"+

            "<form action='/groups/create/' method='post' class='pull-right request-group-form'>"+
              "{% csrf_token %}"+
              "<input type='submit' value='Request group' class='btn btn-primary'>"+
              "<input type='hidden' name='user_id' value='"+user.id+"'>"+
              "<input type='hidden' name='usercourse_id' value='{{usercourse.id}}'>"+
            "</form>"+
            "<strong>Similar availability: </strong>"+(user.availability?"Yes":"No")+"<br>"+
            "<strong>Gender: </strong>"+user.gender+"<br>"+
            "<strong>Description: </strong>"+user.person_type+"<br>"+
            "<strong>Area of study: </strong>"+user.interest+"<br>"+
            "<strong>Age: </strong>"+user.age+"<br>"+
            "<strong>Learning style: </strong>"+user.learning_style+"<br>"+
            "<strong>General level: </strong>"+user.general_level+"<br>"+
            "<strong>Topic level: </strong>"+user.topic_level+"<br>"+
            "<strong>Years of experience: </strong>"+user.years_experience+"<br>"+
            "<strong>Reason for taking: </strong>"+user.reason+"<br>"+
            "<strong>For credit: </strong>"+user.credit+"<br>"+
            "<strong>Goals: </strong>"+user.goals+"<br>"+
            "<strong>Bio: </strong>"+user.bio+
            "<div class='clearfix'></div>"+
          "</div>";
}

function calculateDistance(other){
  var params = {'age':3, 
                'gender':0,
                'person_type':1,
                'learning_style':1, 
                'interest':2,
                'general_level':1, 
                'topic_level':1,
                'years_experience':1, 
                'reason':5,
                'credit':10, 
                'goals': 1};
  var score = 0;
  var max = 0;
  for(var p in params){
    if(user[p] == other[p]){
      score+=params[p];
    }
    max += params[p];
  }
  return (max-score)/max*134+10;
}
</script>

{% endblock %}

app/templates/groups_details.html
{% extends "base.html" %}
{% load availability_check %}
{% block content %}
<h2>{{group}}</h2>
<div class="row">
   <div class="span8">
      <div class="well group-details">
         <div id="messages">
            {% for a in actions %}
            <p><span class="timestamp">{{ a.created|date:"SHORT_DATETIME_FORMAT" }}: </span>
            {% if a.type == 'j' %}
            <span class="user">{{a.user.first_name}}</span> joined the group.
            {% elif a.type == 'c' %}
            <span class="user">{{a.user.first_name}}: </span>{{a.text}}
            {% endif %}
            </p>
            {% endfor %}
         </div>
         <form method="post" class="groups-details-message-form" id="send-message-form">
            {% csrf_token %}
            <textarea name="message" placeholder="Message..." id="message-text"></textarea>
            <input type="submit" value="Send" class="btn btn-inverse">{% if request_video %}<div class="pull-right">Would you like to video chat with this group? <input type="submit" name="video" value="Yes" class="btn btn-inverse"> <input type="submit" name="video" value="No" class="btn btn-inverse"></div>{% endif %}

         </form>
      </div>
   </div>
   <div class="span4">
      {% for p in people %}
      <div class="well">
         <p><strong>{{p.user.first_name}}</strong></p>
         <p>
            <strong>Similar availability: </strong>{% availability_check p.user.get_profile profile "Yes" "No" %}<br>
            <strong>Gender: </strong> {{p.user.get_profile.get_gender_display}}<br>
            <strong>Description: </strong> {{p.user.get_profile.get_person_type_display}}<br>
            <strong>Area of study: </strong> {{p.user.get_profile.get_interest_display}}<br>
            <strong>Age: </strong> {{p.user.get_profile.get_age_display}}<br>
            <strong>Learning style: </strong> {{p.user.get_profile.get_learning_style_display}}<br>
            <strong>General level: </strong> {{p.get_general_level_display}}<br>
            <strong>Topic level: </strong> {{p.get_topic_level_display}}<br>
            <strong>Years of experience: </strong> {{p.get_years_experience_display}}<br>
            <strong>Reason for taking: </strong> {{p.get_reason_display}}<br>
            <strong>For credit: </strong> {{p.get_credit_display}}<br>
            <strong>Goals: </strong> {{p.get_goals_display}}<br>
            <strong>Bio: </strong> {{p.user.get_profile.bio}}
         </p>
      </div>
      {% endfor %}
   </div>
</div>
{% endblock %}
{% block bottom_script %}
<script type="text/javascript"></script>
{% endblock %}

app/templates/main.html
{% extends "base.html" %}
{% block content %}

{% endblock %}

app/templates/partner_request.html
{% extends "base.html" %}
{% load availability_check %}
{% block content %}
<p>The following user has requested to start a group with you for <strong>{{partner_request.course}}</strong></p>
<div class="row">
   <div class="span6 offset3">
      <div class="well">
         <p>
            <strong>Similar availability: </strong>{% availability_check partner_request.user.get_profile partner_request.user.get_profile "Yes" "No" %}<br>
            <strong>Gender: </strong> {{partner_request.owner.get_profile.get_gender_display}}<br>
            <strong>Description: </strong> {{partner_request.owner.get_profile.get_person_type_display}}<br>
            <strong>Description: </strong> {{partner_request.owner.get_profile.get_interest_display}}<br>
            <strong>Age: </strong> {{partner_request.owner.get_profile.get_age_display}}<br>
            <strong>Learning style: </strong> {{partner_request.owner.get_profile.get_learning_style_display}}<br>
            <strong>General level: </strong> {{partner_request.owner_usercourse.get_general_level_display}}<br>
            <strong>Topic level: </strong> {{partner_request.owner_usercourse.get_topic_level_display}}<br>
            <strong>Years of experience: </strong> {{partner_request.owner_usercourse.get_years_experience_display}}<br>
            <strong>Reason for taking: </strong> {{partner_request.owner_usercourse.get_reason_display}}<br>
            <strong>For credit: </strong> {{partner_request.owner_usercourse.get_credit_display}}<br>
            <strong>Goals: </strong> {{partner_request.owner_usercourse.get_goals_display}}<br>
            <strong>Bio: </strong> {{partner_request.owner.get_profile.bio}}
         </p>
         <form method="post" class="pull-right">
            {% csrf_token %}
            <button type="submit" name="reject" value="true" class="btn btn-inverse">Reject</button>
            <button type="submit" name="accept" value="true" class="btn btn-success">Accept</button>
         </form>
         <div class="clearfix"></div>
      </div>
   </div>
</div>

{% endblock %}

app/templates/welcome_account.html
{% extends "base.html" %}
{% load bootstrap %}
{% block content %}
<div class="row">
   <div class="span6">
      <h1>Step 1:</h1>
      <h2>Personal Information</h2>
      <p>Our number one goal is to help you find social groups that will help you succeed in your online courses. To do that we need to know a little more about who you are and how you learn. We will use this data to find people who are similar to you and will work well with you.</p>
   </div>
   <div class="span6">
      <form class="well form-horizontal" method="post">
        {% csrf_token %}
        {{ user_form|bootstrap }}
        {{ user_profile_form|bootstrap }}
        <div class="control-group">
          <div class="controls">
            <button type="submit" class="btn btn-primary">Next</button>
          </div>
        </div>
      </form>
   </div>
</div>
{% endblock %}
{% block bottom_script %}
<script>
function showLearningStyleHelp(){

}

$(document).ready(function(){
  $("#id_bio").bind('input propertychange',function(){
    $("label[for='id_bio']").html("Tell us a little about yourself, ("+(140-$("#id_bio").val().length)+" characters remaining)");
  });

  $("label[for='id_learning_style']").append("<a class='btn btn-link' rel='popover' id='id_learning_style_help' data-content='<strong>Visual</strong>: data and other information is associated with images and techniques.<br><strong>Auditory</strong>: learn by hearing and speaking information.<br><strong>Tactile</strong>: learn by carrying out a physical activity.<br><strong>' data-original-title='Learning Styles'><i class='icon-question-sign'></i></a>");
  $('#id_learning_style_help').popover({'placement':'bottom','html':true,'trigger':'hover'});
});
</script>
{% endblock %}